version: '3.8'

services:
  users-service:
    build: ./users-service/.
    command: ./users-service
    restart: on-failure
    ports:
      - 8001:8000
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=qwerty
      - DB_SSLMODE=disable

  db:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - ./.build/volumes/databases/postgres/data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=qwerty

  gateway:
    image: devopsfaith/krakend:1.2.0
    volumes:
      - ./krakend:/etc/krakend
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8090:8090"
    depends_on:
      - users-service