version: '3.8'

services:
  gateway:
    image: devopsfaith/krakend:1.2.0
    volumes:
      - ./krakend:/etc/krakend
    ports:
      - 8080:8080
    depends_on:
      - users-service
      - file_server

  users-service:
    build: ./users-service/.
    command: ./users-service
    restart: on-failure
    ports:
      - 8001:8000
    depends_on:
      - db
      - file_server
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=users
      - DB_USER=postgres
      - DB_PASS=qwerty
      - DB_SSLMODE=disable
      - TOKEN_AUD=http://gateway:8080
      - TOKEN_ISS=http://users-service:8000
      - PASSWORD_SALT=hhd&S^Ff32HSfB214knamsnflasfj@klfka!

  tasks-service:
    build: ./tasks-service/.
    command: ./tasks-service
    restart: on-failure
    ports:
      - 8003:8000
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=tasks
      - DB_USER=postgres
      - DB_PASS=qwerty
      - DB_SSLMODE=disable

  db:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - ./create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
      - ./.build/volumes/databases/postgres/data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty

  file_server:
    image: jaxgeller/lwan
    volumes:
      - ./data:/lwan/wwwroot
    ports:
      - 8002:8080