version: '3.8'

services:
  gateway:
    image: devopsfaith/krakend:1.2.0
    volumes:
      - ./krakend:/etc/krakend
    ports:
      - 8080:8080
    depends_on:
      - users-service
      - fake_api

  users-service:
    build: ./users-service/.
    command: ./users-service
    restart: on-failure
    ports:
      - 8001:8000
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=qwerty
      - DB_SSLMODE=disable
      - TOKEN_AUD=http://gateway:8080
      - TOKEN_ISS=http://users-service:8000

  db:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - ./.build/volumes/databases/postgres/data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=qwerty

  fake_api:
    image: jaxgeller/lwan
    volumes:
      - ./data:/lwan/wwwroot
    ports:
      - 8002:8080